### ISSUE TITLE
HUD incompatibility with Hephaestus (Tinkers' Constructs)

### ISSUE THREAD

**Issue by ghotiPhoti** [TheDeathlyCow/scorchful#90]
**The bug**
Tinkers' Constructs reworks the HUD by changing the way extra hearts render. Instead of being added above the first layer of hearts, they change colour over the base 10 hearts to indicate extra value, i.e. 15 hearts would appear as 5 orange hearts and 5 red hearts. something about this prevents Frostiful and Scorchful from displaying heat/wetness behind the hearts. 

**To Reproduce**
1. Install Hephaestus with Scorchful & dependencies
2. Stand in an excessively hot or cold climate; in a desert next to a pool of lava will do.
3. There is no indication anywhere on the HUD that you are warm until you receive debuffs and visual/audio effects

**Expected behavior**
A visual heat/cold/wetness gauge

**Game information**
- MC Version 1.20.1
- Quilt Loader 0.26.4, but Fabric experiences the exact same issue.

**Additional context**
Hephaestus has no built-in method to simply disable this feature, so I would probably have to dig into its jar file for things to remove in order to fix this. To be honest i have 0 clue whether this should be posted on their GitHub page or here lol

**Comment by TheDeathlyCow** [comment]
Known issue, a patch is already planned in TheDeathlyCow/thermoo-patches#17 (which I guess makes this technically a duplicate). The issue is actually caused by Mantle, which is bundled in Hephaestus, but you can disable it in the mantle client config by setting `extraHeartRenderer = false` and it should work as normal then. If you really want the rainbow hearts, you can try using colorful hearts, which Thermoo Patches already has an integration patch for.
